### PR TITLE
Python 3 is pumped up, so why are you not using it?

### PR DESCRIPTION
**Pull request by pyarnold**
Hello! My mission is to upgrade you to Python3000. This pull request makes brace tags compatible with Python 3.3. Other frameworks already support python3, like that django thing. I hate django, it is to confusing to pronounce it for an Austrian. I hope the django pony leaves enough room for my fist because I'm going to ram it into its stomach and break its goddamn spine! ARGH!

I will check on this tomorrow morning from the computer room at Gold's. I don't want to see no problem whatsoever.

### CODE REVIEW

**Comment by colevscode** [comment]
Hi Thanks! I'm all for python 3 compatibility, but will these changes preserve 2.6 compatibility? Also, thanks for the style suggestions, but I'd prefer to review those in a separate pull request.

**Comment by pyarnold** [comment]
Did you hear what I just said? I said Python 3 is pumped up, so why do you care about Python 2? Python 2 is damaged goods, lady.

But vaseva, I fixed it between my sets of curls. I'm hungry. Merge my request, it now works in Python 2.6, Python 2.7, and Python 3.3. Ok, trust me, I ran all of your tests and it has to end here.

I was going to add TravisCI (I like saying that out loud) for you tonight, but then you would tell me to put that in another pull request. I know you, you will merge this request now. Do it now! Have a lovely day.

**Comment by colevscode** [comment]
Thanks pyarnold!

**Comment by pyarnold** [comment]
Hey, I'm just doing my job

**Pull request merged**
